// packages/react/src/components/Actions.tsx
import type { ActionsProps } from 'syw-common/types/components'
import { useI18nContext } from '$src/context/i18n'
import { classNames } from 'syw-common/helpers'

const Actions = ({
	actions
}: ActionsProps) => {
	const { getText } = useI18nContext()
	return (
		<div
			className={classNames('Actions')}
		>
			<ul
				className={classNames('ActionsList')}
			>
				{actions.map((action, index) =>
					<li
						key={index}
						className={classNames('ActionsListItem')}
					>
						{getText('action', action)}
					</li>
				)}
			</ul>
		</div>
	)
}

export default Actions

// packages/svelte/src/lib/components/Actions.svelte
<script lang="ts">
	import { classNames } from 'syw-common/helpers'
	import type { ActionsProps } from 'syw-common/types/components'
	import { getI18nContext } from '$lib/store/i18n.js'

	const { actions }: ActionsProps = $props()
	const { locale, getText } = getI18nContext()
</script>

<div
	class={classNames('Actions')}
>
	<ul
		class={classNames('ActionsList')}
	>
		{#each actions as action}
			<li
				class={classNames('ActionsListItem')}
			>
				{getText($locale, 'action', action)}
			</li>
		{/each}
	</ul>
</div>
