// packages/react/src/components/Badge.tsx
import { classNames } from 'syw-common/helpers'
import type { BadgeProps } from 'syw-common/types/components'
import Tooltip from './Tooltip'
import type { TooltipProps } from './Tooltip'
import Icon from './Icon'

interface ReactBadgeProps extends BadgeProps {
	TooltipProps?: Omit<TooltipProps, 'children'>
}

const Badge = ({
	type,
	status,
	TooltipProps: tooltipProps = {},
	children,
	className
}: ReactBadgeProps) => {
	return (
		<Tooltip
			{...tooltipProps}
			ContentProps={{
				...tooltipProps?.ContentProps,
				className: classNames(
					tooltipProps?.ContentProps?.className,
					'BadgeTooltipContent',
					type?.key ? `BadgeTooltipContent_${type?.key}` : null,
					status ? `BadgeTooltipContent_${status}` : null
				),
			}}
			className={classNames(
				'BadgeTooltipTrigger',
				tooltipProps?.className,
			)}
		>
			<span
				className={classNames(
					'Badge',
					className,
					type?.key ? `Badge_${type?.key}` : null,
					status ? `Badge_${status}` : null,
				)}
			>
				<Icon
					type={type?.key ?? status}
					className={classNames('BadgeIcon')}
				/>
				<span
					className='syw-hidden'
				>
					{children}
				</span>
			</span>
		</Tooltip>
	)
}

export default Badge

// packages/svelte/src/lib/components/Badge.svelte
<script lang="ts">
	import { classNames } from 'syw-common/helpers'
	import type { BadgeProps } from 'syw-common/types/components'
    import Tooltip from './Tooltip.svelte'
	import type { TooltipProps } from './Tooltip.svelte'
    import Icon from './Icon.svelte'

	interface Props extends BadgeProps {
		TooltipProps?: Omit<TooltipProps, 'children'>
	}

	const {
		type,
		status,
		TooltipProps: tooltipProps = {},
		children,
		className
	}: Props = $props()
</script>

<Tooltip
	{...tooltipProps}
	// content={typeDefinition()}
	ContentProps={{
		...tooltipProps?.ContentProps,
		className: classNames(
			tooltipProps?.ContentProps?.className,
			'BadgeTooltipContent',
			type?.key ? `BadgeTooltipContent_${type?.key}` : null,
			status ? `BadgeTooltipContent_${status}` : null,
		),
	}}
	className={classNames(
		'BadgeTooltipTrigger',
		tooltipProps?.className,
	)}
>
	<span
		class={classNames(
			'Badge',
			className,
			type?.key ? `Badge_${type?.key}` : null,
			status ? `Badge_${status}` : null,
		)}
	>
		<Icon
			type={type?.key ?? status}
			className={classNames('BadgeIcon')}
		/>
		<span
			class='syw-hidden'
		>
			{@render children?.()}
		</span>
	</span>
</Tooltip>
