// packages/react/src/components/Caption.jsx
import styles from '@syw/common/css/Caption.module.scss'
import { useDataContext } from '$src/context/data'

const Caption = () => {
	const { caption, byline } = useDataContext()
	return caption || byline ? (
		<figcaption
			className={styles.Caption}
		>
			<div
				className={styles.CaptionInner}
			>
				{caption}&nbsp;
				<em
					className={styles.CaptionByline}
				>
					{byline}
				</em>
			</div>
		</figcaption>
	) : null
}

export default Caption

// packages/svelte/src/lib/components/Caption.svelte
<script>
	import styles from 'syw-common/css/Caption.module.scss'
	import { caption, byline } from '$lib/store/data.js'

</script>

{#if $caption || $byline}
	<!-- svelte-ignore a11y-structure -->
	<figcaption
		class={styles.Caption}
	>
		<div
			class={styles.CaptionInner}
		>
			{$caption}&nbsp;
			<em
				class={styles.CaptionByline}
			>
				{$byline}
			</em>
		</div>
	</figcaption>
{/if}
