// packages/react/src/components/Cutline.jsx
import styles from 'syw-common/css/Cutline.module.scss'
import ToggleProvenance from './ToggleProvenance'
import ToggleExplainer from './ToggleExplainer'

const Cutline = ({
	caption,
	byline
}) => {
	return (
		<div
			className={styles.Cutline}
		>
			<div
				className={styles.CutlineToggles}
			>
				<ToggleProvenance />
				<ToggleExplainer />
			</div>
		</div>
	)
}

export default Cutline

// packages/svelte/src/lib/components/Cutline.svelte
<script>
	import styles from '@syw/common/css/Cutline.module.scss'
	import ToggleProvenance from './ToggleProvenance.svelte'
	import ToggleExplainer from './ToggleExplainer.svelte'
</script>

<div
	class={styles.Cutline}
>
	<div
		class={styles.CutlineToggles}
	>
		<ToggleProvenance />
		<ToggleExplainer />
	</div>
</div>
