// packages/react/src/components/Explainer.jsx
import React from 'react'

import styles from '$common/css/Explainer.module.scss'
import { useI18nContext } from '$src/context/i18n'
import { useUiContext } from '$src/context/ui'
import Collapse from './Collapse'

const Explainer = () => {
	const { getText } = useI18nContext()
	const {
		isShowExplainer,
		toggleExplainer
	} = useUiContext()

	const onCloseClick = toggleExplainer

	return (
		<div
			className={styles.Explainer}
		>
			<Collapse
				open={isShowExplainer}
			>
				<div
					className={styles.ExplainerInner}
				>
					<button
						className={styles.ExplainerClose}
						aria-pressed={isShowExplainer}
						onClick={onCloseClick}
					>
						{getText('toggle', 'explain', 'close')}
					</button>
					<div>
						<strong>
							Consectetur adipiscing elit
						</strong>
					</div>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris enim nibh, rhoncus vel enim ac, luctus efficitur risus. Quisque viverra tellus vitae arcu consectetur tincidunt. Ut vel pharetra tellus. Nam posuere suscipit maximus.</p>
					<div>
						<strong>
							Cras sagittis erat
						</strong>
					</div>
					<p>Suspendisse a neque nulla. Cras sagittis erat sed elit tristique, a efficitur ante malesuada. Quisque dapibus pharetra dictum.</p>
					<div
						className={styles.ExplainerMore}
					>
						{getText('explainer', 'methods', 'pre')}&nbsp;
						<a
							href={getText('explainer', 'methods', 'url')}
							// target='_blank'
							// rel='noreferrer noopener'
						>
							{getText('explainer', 'methods', 'link')}
						</a>
					</div>
				</div>
			</Collapse>
		</div>
	)
}

export default Explainer

// packages/svelte/src/lib/components/Explainer.svelte
<script>
	import styles from '$common/css/Explainer.module.scss'
	import { locale, getText } from '$lib/store/i18n'
	import { isShowExplainer, toggleExplainer } from '$lib/store/ui'
	import Collapse from './Collapse.svelte'

	const onCloseClick = () => {
		toggleExplainer()
	}
</script>

<div
	class={styles.Explainer}
>
	<Collapse
		open={$isShowExplainer}
	>
		<div
			class={styles.ExplainerInner}
		>
			<button
				class={styles.ExplainerClose}
				aria-pressed={$isShowExplainer}
				on:click={onCloseClick}
			>
				{getText($locale, 'toggle', 'explain', 'close')}
			</button>
			<div>
				<strong>
					Consectetur adipiscing elit
				</strong>
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris enim nibh, rhoncus vel enim ac, luctus efficitur risus. Quisque viverra tellus vitae arcu consectetur tincidunt. Ut vel pharetra tellus. Nam posuere suscipit maximus.</p>
			<div>
				<strong>
					Cras sagittis erat
				</strong>
			</div>
			<p>Suspendisse a neque nulla. Cras sagittis erat sed elit tristique, a efficitur ante malesuada. Quisque dapibus pharetra dictum.</p>
			<div
				class={styles.ExplainerMore}
			>
				{getText($locale, 'explainer', 'methods', 'pre')}
				<a
					href={getText($locale, 'explainer', 'methods', 'url')}
					target='_blank'
					rel='noreferrer noopener'
				>
					{getText($locale, 'explainer', 'methods', 'link')}
				</a>
			</div>
		</div>
	</Collapse>
</div>
