// packages/react/src/components/ManifestTable.jsx
import styles from 'syw-common//css/Manifest.module.scss'
import { MANIFEST_KEYS } from 'syw-common//constants'
import ManifestTableRow from './ManifestTableRow'

function ManifestTable({ manifest }) {
	return (
		<ul
			className={styles.ManifestTable}
		>
			{MANIFEST_KEYS.map(key =>
				manifest[key] ?
					<ManifestTableRow
						key={key}
						type={key}
						value={manifest[key]}
					/>
				: null
			)}
			{manifest?.verifyUrl ?
				<li>
					<a
						href={manifest?.verifyUrl}
						target='_blank'
					>
						View Content Credentials
					</a>
				</li>
			: null}
		</ul>
	)
}

export default ManifestTable

// packages/svelte/src/lib/components/ManifestTable.svelte
<script>
	import styles from '$common/css/Manifest.module.scss'
	import { MANIFEST_KEYS } from '$common/constants'
	import ManifestTableRow from './ManifestTableRow.svelte'

	export let manifest
</script>

<ul
	class={styles.ManifestTable}
>
	{#each MANIFEST_KEYS as key}
		{#if manifest[key]}
			<ManifestTableRow
				type={key}
				value={manifest[key]}
			/>
		{/if}
	{/each}
	<!-- {manifest?.verifyUrl ?
		<li>
			<a
				href={manifest?.verifyUrl}
				target='_blank'
			>
				View Content Credentials
			</a>
		</li>
	: null} -->
</ul>
