// packages/react/src/components/ManifestTable.tsx
import { classNames } from 'syw-common/helpers'
import type { ManifestTableProps } from 'syw-common/types/components'
import ManifestTableRow from './ManifestTableRow'

function ManifestTable({ keys = [], manifest }: ManifestTableProps) {
	return (
		<ul
			className={classNames('ManifestTable')}
		>
			{keys.map(key =>
				<ManifestTableRow
					key={key}
					type={key}
					value={manifest[key]}
					manifest={manifest}
				/>
			)}
		</ul>
	)
}

export default ManifestTable

// packages/svelte/src/lib/components/ManifestTable.svelte
<script>
	import { classNames } from 'syw-common/helpers'
	import ManifestTableRow from './ManifestTableRow.svelte'

	const {
		keys = [],
		manifest = {}
	} = $props()
</script>

<ul
	class={classNames('ManifestTable')}
>
	{#each keys as key}
		{#if manifest[key]}
			<ManifestTableRow
				type={key}
				value={manifest[key]}
				manifest={manifest}
			/>
		{/if}
	{/each}
</ul>
