// packages/react/src/components/ManifestContentTabsToggle.jsx
import { useMemo } from 'react'
import { Tabs } from '@ark-ui/react/tabs'
import { useI18nContext } from '$src/context'
import { classNames, getObjectValue } from 'syw-common/helpers'

function ManifestContentTabsToggle({
	manifest,
	keys
}) {
	const { getText } = useI18nContext()
	
	const disabledTabKeys = useMemo(() =>
		keys?.filter(key => {
			const value = getObjectValue(key, manifest)
			if(key === "location") {
				return !value
			} else if(key === "actions") {
				return !value?.length
			} else {
				return false
			}
		})
	, [keys, manifest]);

	return (
		<div
			className={classNames('ManifestContentTabsToggle')}
		>
			<Tabs.List
				className={classNames('ManifestContentTabsToggleList')}
			>
				{keys?.map((key) => (
					<Tabs.Trigger
						key={key}
						value={key}
						disabled={disabledTabKeys.includes(key)}
						className={classNames('ManifestContentTabsToggleTrigger')}
					>
						{getText("tab", key)}
					</Tabs.Trigger>
				))}
				<Tabs.Indicator
					className={classNames('ManifestContentTabsToggleListIndicator')}
				/>
			</Tabs.List>
		</div>
	)
}

export default ManifestContentTabsToggle

// packages/svelte/src/lib/components/ManifestContentTabsToggle.svelte
<script>
    import { getContext } from 'svelte';
	import { Tabs } from '@ark-ui/svelte/tabs'
	import { classNames, getObjectValue } from 'syw-common/helpers'

	const {
		keys = [],
		manifest = {}
	} = $props()

	const { locale, getText } = getContext('i18nStoreContext')

	const disabledTabKeys = $derived(() =>
		keys?.filter(key => {
			const value = getObjectValue(key, manifest)
			if(key === "location") {
				return !value
			} else if(key === "actions") {
				return !value?.length
			} else {
				return false
			}
		})
	);

</script>

<div
	class={classNames('ManifestContentTabsToggle')}
>
	<Tabs.List
		class={classNames('ManifestContentTabsToggleList')}
	>
		{#each keys as key}
			<Tabs.Trigger
				value={key}
				disabled={disabledTabKeys().includes(key)}
				class={classNames('ManifestContentTabsToggleTrigger')}
			>
				{getText($locale, "tab", key)}
			</Tabs.Trigger>
		{/each}
		<Tabs.Indicator
			class={classNames('ManifestContentTabsToggleListIndicator')}
		/>
	</Tabs.List>
</div>
