// packages/react/src/components/ManifestContentTabs.tsx
import { useMemo } from 'react'
import { Tabs } from '@ark-ui/react/tabs'
import { classNames, getAvailableTabs } from 'syw-common/helpers'
import type { ManifestContentTabsProps } from 'syw-common/types/components'
import Map from './Map'
import Actions from './Actions'
import Icon from './Icon'

function ManifestContentTabs({
	manifest,
	keys
}: ManifestContentTabsProps) {
	const availableTabs = useMemo(() =>
		getAvailableTabs(keys, manifest)
	, [keys, manifest])
	
	return (
		<div
			className={classNames('ManifestContentTabs')}
		>
			{availableTabs?.map((key) => (
				<Tabs.Content
					key={key}
					value={key}
					className={classNames(
						'ManifestContentTabsContent',
						`ManifestContentTabsContent_${key}`
					)}
				>
					<div
						className={classNames('ManifestContentTabsContentInner')}
					>
						{key === "thumbnail" ?
							<div
								className={classNames(
									'ManifestContentTabsThumbnail',
									!manifest?.thumbnail ? 'ManifestContentTabsThumbnail_missing' : null,
								)}
							>
								{manifest?.thumbnail ?
									<img
										alt=''
										src={manifest?.thumbnail ?? undefined}
										className={classNames('ManifestContentTabsThumbnailImage')}
									/>
								: <Icon type="missing" />}
							</div>
						: key === "location" && manifest?.location ?
							<Map
								location={manifest?.location}
							/>
						: key === "actions" ?
							<Actions
								actions={manifest?.actions ?? []}
							/>
						: null}
					</div>
				</Tabs.Content>
			))}
		</div>
	)
}

export default ManifestContentTabs

// packages/svelte/src/lib/components/ManifestContentTabs.svelte
<script lang="ts">
	import { Tabs } from '@ark-ui/svelte/tabs'
	import { classNames, getAvailableTabs } from 'syw-common/helpers'
	import type { ManifestContentTabsProps } from 'syw-common/types/components'
	import Map from './Map.svelte'
	import Actions from './Actions.svelte'
	import Icon from './Icon.svelte'

	const {
		manifest,
		keys = [],
	}: ManifestContentTabsProps = $props()

	const availableTabs = $derived(() =>
		getAvailableTabs(keys, manifest)
	)
</script>

<div
	class={classNames('ManifestContentTabs')}
>
	{#each availableTabs() as key}
		<Tabs.Content
			value={key}
			class={classNames(
				'ManifestContentTabsContent',
				`ManifestContentTabsContent_${key}`
			)}
		>
			<div
				class={classNames('ManifestContentTabsContentInner')}
			>
				{#if key === "thumbnail"}
					<div
						class={classNames(
							'ManifestContentTabsThumbnail',
							!manifest?.thumbnail ? 'ManifestContentTabsThumbnail_missing' : null,
						)}
					>
						{#if manifest?.thumbnail}
							<img
								alt=''
								src={manifest?.thumbnail}
								class={classNames('ManifestContentTabsThumbnailImage')}
							/>
						{:else}
							<Icon type="missing" />
						{/if}
					</div>
				{:else if key === "location" && manifest?.location}
					<Map
						location={manifest?.location}
					/>
				{:else if key === "actions"}
					<Actions
						actions={manifest?.actions ?? []}
					/>
				{/if}
			</div>
		</Tabs.Content>
	{/each}
</div>
