// packages/react/src/components/ManifestPreview.jsx
import { MANIFEST_PREVIEW_TITLE_KEYS } from 'syw-common/constants'
import { handleA11yClick, classNames } from 'syw-common/helpers'
import { getDateString } from 'syw-common/helpers/i18n'
import { useI18nContext } from '$src/context/i18n'
import { useUiContext } from '$src/context/ui'
import Badge from '$src/components/Badge'

function ManifestPreview({
	manifest,
	toggled,
	onToggle,
	previewRef
}) {
	const { locale, getText } = useI18nContext()
	const { thumbnail, openThumbnail, closeThumbnail, addThumbnail, removeThumbnail, updateThumbnailPosition } = useUiContext()
	const thumbnailUrl = manifest?.thumbnail?.value
	
	const onKeyDown = event => {
		handleA11yClick(event, onToggle)
	}
	const onThumbnailMouseMove = event => {
		updateThumbnailPosition(event)
	}
	const onThumbnailMouseEnter = event => {
		openThumbnail(event)
		addThumbnail(thumbnailUrl, event)
	}
	const onThumbnailMouseLeave = event => {
		closeThumbnail(event)
		removeThumbnail(event)
	}

	return (
		<div
			ref={previewRef}
			role='button'
			tabIndex={0}
			aria-pressed={toggled}
			className={classNames('ManifestPreview')}
			onClick={onToggle}
			onKeyDown={onKeyDown}
		>
			<div
				className={classNames('ManifestPreviewBadge')}
			>
				<Badge
					type={manifest.type}
					status={manifest.status}
				/>
			</div>
			<div
				className={classNames('ManifestPreviewCells')}
			>
				<div
					className={classNames(
						'ManifestPreviewCell',
						'ManifestPreviewCell_issuer'
					)}
				>
					{manifest.type?.key
						? getText("type", manifest.type?.key)
						: MANIFEST_PREVIEW_TITLE_KEYS.filter(key => manifest[key]).map(key =>
							manifest[key]?.value
						).join(" ")
					}
				</div>
				<div
					className={classNames(
						'ManifestPreviewCell',
						'ManifestPreviewCell_time'
					)}
				>
					<span>{getDateString(locale, manifest.timestamp.value)}</span>
				</div>
				<div
					className={classNames(
						'ManifestPreviewCell',
						'ManifestPreviewCell_thumb',
						thumbnailUrl === thumbnail
							? 'ManifestPreviewCell_thumb_hover'
							: null
					)}
					onMouseMove={onThumbnailMouseMove}
					onMouseEnter={onThumbnailMouseEnter}
					onMouseLeave={onThumbnailMouseLeave}
				>
					<img
						src={thumbnailUrl}
						alt=''
					/>
				</div>
			</div>
		</div>
	)
}

export default ManifestPreview

// packages/svelte/src/lib/components/ManifestPreview.svelte
<script>
	import { getContext } from 'svelte';
	import { classNames } from 'syw-common/helpers'
	import { MANIFEST_PREVIEW_TITLE_KEYS } from 'syw-common/constants'
	import { handleA11yClick } from 'syw-common/helpers'
	import { getDateString } from 'syw-common/helpers/i18n'
    import Badge from './Badge.svelte';

	const {
		open,
		manifest
	} = $props()

	const { locale, getText } = getContext('i18nStoreContext');
	const {
		openManifest, closeManifest, updateThumbnailPosition, openThumbnail, closeThumbnail, addThumbnail, removeThumbnail
	} = getContext('uiStoreContext');

	const handleClick = (event => {
		if(open) {
			closeManifest(event, manifest)
		} else {
			openManifest(event, manifest)
		}
	})

	const handleKeyDown = event => {
		handleA11yClick(event, handleClick)
	}

	const handleThumbnailMouseMove = event => {
		updateThumbnailPosition(event)
	}
	const handleThumbnailMouseEnter = event => {
		openThumbnail(event)
		addThumbnail(manifest?.thumbnail, event)
	}
	const handleThumbnailMouseLeave = event => {
		closeThumbnail(event)
		removeThumbnail(event)
	}

</script>

<div
	role='button'
	tabindex={0}
	aria-pressed={open}
	class={classNames('ManifestPreview')}
	onclick={handleClick}
	onkeydown={handleKeyDown}
>
	<div
		class={classNames('ManifestPreviewBadge')}
	>
		<Badge
			type={manifest.type}
			status={manifest.status}
		/>
	</div>
	<div
		class={classNames('ManifestPreviewCells')}
	>
		<div
			class={classNames('ManifestPreviewCell', 'ManifestPreviewCell_issuer')}
		>
			{manifest.type?.key
				? getText($locale, 'type', manifest.type?.key)
				: MANIFEST_PREVIEW_TITLE_KEYS.filter(key => manifest[key]).map(key =>
					manifest[key]?.value
				).join(" ")}
		</div>
		<div
			class={classNames('ManifestPreviewCell', 'ManifestPreviewCell_time')}
		>
			<span>{getDateString($locale, manifest?.timestamp.value) ?? ''}</span>
		</div>
		<div
			role='button'
			tabindex={0}
			class={classNames('ManifestPreviewCell', 'ManifestPreviewCell_thumb')}
			onmousemove={handleThumbnailMouseMove}
			onmouseenter={handleThumbnailMouseEnter}
			onmouseleave={handleThumbnailMouseLeave}
		>
			{#if manifest?.thumbnail?.value}
				<img
					src={manifest?.thumbnail?.value}
					alt=''
				/>
			{/if}
		</div>
	</div>
</div>
