// packages/react/src/components/ManifestPreview.tsx
import type { KeyboardEvent, RefObject } from 'react'
import { MANIFEST_PREVIEW_TITLE_KEYS } from 'syw-common/constants'
import { handleA11yClick, classNames } from 'syw-common/helpers'
import { getDateString } from 'syw-common/helpers/i18n'
import type { ManifestPreviewProps } from 'syw-common/types/components'
import { useI18nContext } from '$src/context/i18n'
import Badge from '$src/components/Badge'
import Icon from '$src/components/Icon'
import ManifestContentTabsToggle from './ManifestContentTabsToggle'

interface ReactManifestPreviewProps extends ManifestPreviewProps {
	previewRef: RefObject<HTMLDivElement> | null
}

function ManifestPreview({
	open,
	manifest,
	tabKeys,
	onToggle,
	previewRef
}: ReactManifestPreviewProps) {
	const { locale, getText } = useI18nContext()
	const thumbnailUrl = manifest?.thumbnail

	const onKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
		handleA11yClick(event, onToggle)
	}

	return (
		<div
			className={classNames('ManifestPreview')}
		>
			<div
				ref={previewRef}
				role='button'
				tabIndex={0}
				aria-pressed={open}
				className={classNames('ManifestPreviewToggle')}
				onClick={onToggle}
				onKeyDown={onKeyDown}
			>
				<div
					className={classNames('ManifestPreviewBadge')}
				>
					<Badge
						type={manifest.type}
						status={manifest.status}
					/>
				</div>
				<div
					className={classNames('ManifestPreviewCells')}
				>
					<div
						className={classNames(
							'ManifestPreviewCell',
							'ManifestPreviewCell_issuer'
						)}
					>
						{manifest.type?.key
							? getText("type", manifest.type?.key)
							: MANIFEST_PREVIEW_TITLE_KEYS.filter(key => manifest[key]).map(key =>
								manifest[key]
							).join(" ")
						}
					</div>
					<div
						className={classNames(
							'ManifestPreviewCell',
							'ManifestPreviewCell_time'
						)}
					>
						<span>{getDateString(locale, manifest?.timestamp ?? undefined)}</span>
					</div>
					<div
						className={classNames(
							'ManifestPreviewCell',
							'ManifestPreviewCell_thumb',
						)}
					>
						{thumbnailUrl ?
							<img
								src={thumbnailUrl}
								alt=''
							/>
						: <Icon type="missing" />}
					</div>
				</div>
			</div>
			<ManifestContentTabsToggle
				keys={tabKeys}
				manifest={manifest}
				className={classNames('ManifestPreviewTabsToggle')}
			/>
		</div>
	)
}

export default ManifestPreview

// packages/svelte/src/lib/components/ManifestPreview.svelte
<script>
	import { getContext } from 'svelte';
	import { classNames } from 'syw-common/helpers'
	import { MANIFEST_PREVIEW_TITLE_KEYS } from 'syw-common/constants'
	import { handleA11yClick } from 'syw-common/helpers'
	import { getDateString } from 'syw-common/helpers/i18n'
    import Badge from './Badge.svelte';
    import ManifestContentTabsToggle from './ManifestContentTabsToggle.svelte';

	const {
		manifest,
		tabKeys,
		open,
	} = $props()

	const { locale, getText } = getContext('i18nStoreContext');
	const {
		openManifest, closeManifest, updateThumbnailPosition, openThumbnail, closeThumbnail, addThumbnail, removeThumbnail
	} = getContext('uiStoreContext');

	const handleClick = (event => {
		if(open) {
			closeManifest(event, manifest)
		} else {
			openManifest(event, manifest)
		}
	})

	const handleKeyDown = event => {
		handleA11yClick(event, handleClick)
	}

	const handleThumbnailMouseMove = event => {
		updateThumbnailPosition(event)
	}
	const handleThumbnailMouseEnter = event => {
		openThumbnail(event)
		addThumbnail(manifest?.thumbnail, event)
	}
	const handleThumbnailMouseLeave = event => {
		closeThumbnail(event)
		removeThumbnail(event)
	}

</script>

<div
	class={classNames('ManifestPreview')}
>
	<div
		role='button'
		tabindex={0}
		aria-pressed={open}
		class={classNames('ManifestPreviewToggle')}
		onclick={handleClick}
		onkeydown={handleKeyDown}
	>
		<div
			class={classNames('ManifestPreviewBadge')}
		>
			<Badge
				type={manifest.type}
				status={manifest.status}
			/>
		</div>
		<div
			class={classNames('ManifestPreviewCells')}
		>
			<div
				class={classNames('ManifestPreviewCell', 'ManifestPreviewCell_issuer')}
			>
				{manifest.type?.key
					? getText($locale, 'type', manifest.type?.key)
					: MANIFEST_PREVIEW_TITLE_KEYS.filter(key => manifest[key]).map(key =>
						manifest[key]
					).join(" ")}
			</div>
			<div
				class={classNames('ManifestPreviewCell', 'ManifestPreviewCell_time')}
			>
				<span>{getDateString($locale, manifest?.timestamp) ?? ''}</span>
			</div>
			<div
				role='button'
				tabindex={0}
				class={classNames('ManifestPreviewCell', 'ManifestPreviewCell_thumb')}
				onmousemove={handleThumbnailMouseMove}
				onmouseenter={handleThumbnailMouseEnter}
				onmouseleave={handleThumbnailMouseLeave}
			>
				{#if manifest?.thumbnail}
					<img
						src={manifest?.thumbnail}
						alt=''
					/>
				{/if}
			</div>
		</div>
	</div>
	<ManifestContentTabsToggle
		keys={tabKeys}
		manifest={manifest}
	/>
</div>
