// packages/react/src/components/ManifestContentTabs.jsx
import { Tabs } from '@ark-ui/react/tabs'
import { useI18nContext } from '$src/context'
import { classNames } from 'syw-common/helpers'
import Map from './Map'
import Actions from './Actions'

function ManifestContentTabs({
	manifest,
	keys
}) {
	const { getText } = useI18nContext()
	
	return (
		<div
			className={classNames('ManifestContentTabs')}
		>
			{keys?.map((key) => (
				<Tabs.Content
					key={key}
					value={key}
					className={classNames(
						'ManifestContentTabsContent',
						`ManifestContentTabsContent_${key}`
					)}
				>
					<div
						className={classNames('ManifestContentTabsContentInner')}
					>
						{key === "thumbnail" ?
							<div
								className={classNames('ManifestContentTabsThumbnail')}
							>
								<img
									alt=''
									src={manifest?.thumbnail}
									className={classNames('ManifestContentTabsThumbnailImage')}
								/>
							</div>
						: key === "location" && manifest?.location ?
							<Map
								location={manifest?.location}
							/>
						: key === "actions" ?
							<Actions
								actions={manifest?.actions}
							/>
						: null}
					</div>
				</Tabs.Content>
			))}
		</div>
	)
}

export default ManifestContentTabs

// packages/svelte/src/lib/components/ManifestContentTabs.svelte
<script>
	import { Tabs } from '@ark-ui/svelte/tabs'
	import { classNames } from 'syw-common/helpers'
	import Map from './Map.svelte'
	import Actions from './Actions.svelte'

	const {
		manifest = {},
		keys = [],
	} = $props()

</script>

<div
	class={classNames('ManifestContentTabs')}
>
	{#each keys as key}
		<Tabs.Content
			value={key}
			class={classNames(
				'ManifestContentTabsContent',
				`ManifestContentTabsContent_${key}`
			)}
		>
			<div
				class={classNames('ManifestContentTabsContentInner')}
			>
				{#if key === "thumbnail"}
					<div
						class={classNames('ManifestContentTabsThumbnail')}
					>
						<img
							alt=''
							src={manifest?.thumbnail}
							class={classNames('ManifestContentTabsThumbnailImage')}
						/>
					</div>
				{:else if key === "location"}
					<Map
						location={manifest?.location}
					/>
				{:else if key === "actions"}
					<Actions
						actions={manifest?.actions}
					/>
				{/if}
			</div>
		</Tabs.Content>
	{/each}
</div>
