// packages/react/src/components/ProvenanceToggle.tsx
import type { MouseEvent } from 'react'
import { classNames } from 'syw-common/helpers'
import { useI18nContext, useDataContext, useUiContext } from '$src/context'
import Badge from './Badge'

const ProvenanceToggle = () => {
	const { getText } = useI18nContext()
	const { status } = useDataContext()
	const { isProvenanceOpen, openProvenance, closeProvenance } = useUiContext()

	const onClick = (event: MouseEvent<HTMLButtonElement>) => isProvenanceOpen
		? closeProvenance(event)
		: openProvenance(event)

	return (
		<button
			aria-pressed={isProvenanceOpen}
			className={classNames('ProvenanceToggle')}
			onClick={onClick}
		>
			<Badge
				// type={types[0]}
				status={status}
				TooltipProps={{
					disabled: true
				}}
			/>
			<span>
				{isProvenanceOpen ? getText('provenance', 'toggle') : getText('provenance', 'toggle')}
			</span>
		</button>
	)
}

export default ProvenanceToggle

// packages/svelte/src/lib/components/ProvenanceToggle.svelte
<script lang="ts">
	import { classNames } from 'syw-common/helpers'
	import Badge from './Badge.svelte';
	import { getDataContext } from '$lib/store/data.js'
	import { getI18nContext } from '$lib/store/i18n.js'
	import { getUiContext } from '$lib/store/ui.js'

	const { locale, getText } = getI18nContext();
	const { status, types } = getDataContext();
	const { isProvenanceOpen, openProvenance, closeProvenance } = getUiContext();

	const handleClick = (event: MouseEvent) => {
		if($isProvenanceOpen) {
			closeProvenance(event)
		} else {
			openProvenance(event)
		}
	}

</script>

<button
	aria-pressed={$isProvenanceOpen}
	class={classNames('ProvenanceToggle')}
	onclick={handleClick}
>
	<Badge
		status={$status}
		TooltipProps={{
			disabled: true
		}}
	/>
	<span>
		{$isProvenanceOpen ? getText($locale, 'provenance', 'toggle') : getText($locale, 'provenance', 'toggle')}
	</span>
</button>
