// packages/react/src/components/Thumbnail.tsx
import { classNames } from 'syw-common/helpers'
import { useUiContext } from '$src/context/ui'
import { useI18nContext } from '$src/context/i18n'

const Thumbnail = () => {
	const {
		thumbnail,
		thumbnailPosition
	} = useUiContext()
	const { getText } = useI18nContext()

	return (
		<div
			className={classNames('Thumbnail')}
			style={{
				left: `${thumbnailPosition?.clientX}px`,
				top: `${thumbnailPosition?.clientY}px`,
			}}
		>
			{thumbnail ?
				<img
					src={thumbnail}
					alt={""}
					className={classNames('ThumbnailImg')}
				/>
			: null}
			{!thumbnail ?
				<div
					className={classNames('ThumbnailMissing')}
				>
					{getText('thumbnail', 'missing')}
				</div>
			: null}
		</div>
	)
}

export default Thumbnail

// packages/svelte/src/lib/components/Thumbnail.svelte
<script lang="ts">
	import { classNames } from 'syw-common/helpers'
	import { getI18nContext } from '$lib/store/i18n.js'
	import { getUiContext } from '$lib/store/ui.js'

	const {
		thumbnail,
		thumbnailPosition
	} = getUiContext()

	const { locale, getText } = getI18nContext();

</script>

<div
	class={classNames('Thumbnail')}
	style={`left:${$thumbnailPosition?.clientX}px;top:${$thumbnailPosition?.clientY}px`}
>
	{#if $thumbnail}
		<img
			src={$thumbnail}
			alt={""}
			class={classNames('ThumbnailImg')}
		/>
	{:else}
		<div
			class={classNames('ThumbnailMissing')}
		>
			{getText($locale, 'thumbnail', 'missing')}
		</div>
	{/if}
</div>
