// packages/svelte/src/lib/components/Actions.svelte
<script>
	import { getContext } from 'svelte';
	import { classNames } from 'syw-common/helpers'

	const { actions } = $props()
	const { locale, getText } = getContext('i18nStoreContext')
</script>

<div
	class={classNames('Actions')}
>
	<ul
		class={classNames('ActionsList')}
	>
		{#each actions as action}
			<li
				class={classNames('ActionsListItem')}
			>
				{getText($locale, 'action', action)}
			</li>
		{/each}
	</ul>
</div>

// packages/react/src/components/Actions.jsx
import { useEffect, useId, useState } from 'react'
import { classNames } from 'syw-common/helpers'
import { useI18nContext } from '$src/context/i18n'
// import { getLangFromLocale } from 'syw-common/helpers/i18n'
const Actions = ({
	actions
}) => {
	const { locale, getText } = useI18nContext()
	return (
		<div
			className={classNames('Actions')}
		>
			<ul
				className={classNames('ActionsList')}
			>
				{actions.map((action, index) =>
					<li
						key={index}
						className={classNames('ActionsListItem')}
					>
						{getText('action', action)}
					</li>
				)}
			</ul>
		</div>
	)
}

export default Actions
