// packages/svelte/src/lib/components/App.svelte
<script>
	import { onMount } from 'svelte';
	import { createC2pa } from 'c2pa';
	import wasmSrc from 'c2pa/dist/assets/wasm/toolkit_bg.wasm?url';
	import workerSrc from 'c2pa/dist/c2pa.worker.min.js?url';
	import 'syw-common/css/globals.scss'
	import styles from 'syw-common/css/App.module.scss'
	import { joinClassNames } from 'syw-common/helpers'
	import { prepareManifest } from 'syw-common/helpers/c2pa'
	import { lang, setLocale } from '$lib/store/i18n.js'
	import { setSrc, setAlt, setCaption, setByline, setManifests } from '$lib/store/data.js'
	import { isHoverImage, isProvenanceOpen, setEventHandler } from '$lib/store/ui.js'
	import Figure from './Figure.svelte'
	import Image from './Image.svelte'
	import Explainer from './Explainer.svelte'
	import Cutline from './Cutline.svelte'
	import Caption from './Caption.svelte'
	import Provenance from './Provenance.svelte'

	export let src = ''
	export let alt = ''
	export let caption = ''
	export let byline = ''
	export let locale = ''
	export let onEvent = null

	$: setSrc(src)
	$: setAlt(alt)
	$: setCaption(caption)
	$: setByline(byline)
	$: setLocale(locale)
	$: setEventHandler(onEvent)

	const update = async () => {
		const c2pa = await createC2pa({
			wasmSrc,
			workerSrc,
		})
		try {
			// Read in the image and get a manifest store
			const { manifestStore } = await c2pa.read(src);
			// Get the active manifest
			const newManifests = Object.values(manifestStore?.manifests ?? {})
				.map(manifest => prepareManifest(locale, manifest))
			// Set manifests to data store
			setManifests(newManifests)
		} catch (err) {
			console.error('Error reading image:', err);
		}
	}

	onMount(() => {
		update(src)
	});
	// $: update(), [src]

	$: classes = joinClassNames(
		styles.App,
		$isHoverImage ? styles.App_hovered : false,
		$isProvenanceOpen ? styles.App_active : false
	)

</script>

<div
	class={classes}
	lang={$lang}
>
	<Figure>
		<Image />
		<Explainer />
		<Cutline />
		<Caption />
	</Figure>
	<Provenance />
</div>

// packages/react/src/components/App.jsx
import { useEffect, useMemo, useRef } from 'react'
import { useC2pa } from '@contentauth/react'
import styles from 'syw-common/css/App.module.scss'
import { joinClassNames } from 'syw-common/helpers'
import { prepareManifest } from 'syw-common/helpers/c2pa'
import { useDataContext } from '$src/context/data'
import { useI18nContext } from '$src/context/i18n'
import { useUiContext } from '$src/context/ui'
import Figure from './Figure'
import Image from './Image'
import Cutline from './Cutline'
import Caption from './Caption'
import Explainer from './Explainer'
import Provenance from './Provenance'
import Collapse from './Collapse'
import '$src/globals.scss'

function App({
	onEvent
}) {
	const ref = useRef(null)
	const { src, setManifests } = useDataContext()
	const { locale } = useI18nContext()
	const { isHoverImage, isOpenProvenance, eventHandler } = useUiContext()
	const provenance = useC2pa(src)

	const className = useMemo(() =>
		joinClassNames(
			styles.App,
			isHoverImage ? styles.App_hovered : false,
			isOpenProvenance ? styles.App_active : false
		)
	, [isHoverImage, isOpenProvenance])

	useEffect(() => {
		const manifestStore = provenance?.manifestStore
		const newManifests = Object.values(manifestStore?.manifests ?? {})
			.map(manifest => prepareManifest(locale, manifest))
		setManifests(newManifests)
	}, [locale, provenance])

	useEffect(() => {
		eventHandler.current = onEvent
	}, [eventHandler, onEvent])

	// useEffect(() => {
	// 	const time = new Date();
	// 	if(onProvenanceToggle) onProvenanceToggle(isOpenProvenance, ref.current, time)
	// }, [isOpenProvenance, ref])

	return (
		<div
			ref={ref}
			className={className}
		>
			<Figure>
				<Image />
				<Explainer />
				<Cutline />
				<Caption />
			</Figure>
			<Collapse
				open={isOpenProvenance}
			>
				<Provenance />
			</Collapse>
		</div>
	)
}

export default App
