// packages/svelte/src/lib/components/Caption.svelte
<script lang="ts">
	import { classNames } from 'syw-common/helpers'
    import Markdown from './Markdown.svelte';
	import { getDataContext } from '$lib/store/data.js'

	const { caption, byline } = getDataContext();
</script>

{#if $caption || $byline}
	<!-- svelte-ignore a11y_figcaption_parent -->
	<figcaption
		class={classNames('Caption')}
	>
		<div
			class={classNames('CaptionInner')}
		>
			<Markdown
				content={$caption}
			/>
			<div
				class={classNames('CaptionByline')}
			>
				{$byline}
			</div>
		</div>
	</figcaption>
{/if}

// packages/react/src/components/Caption.tsx
import { classNames } from 'syw-common/helpers'
import { useDataContext } from '$src/context/data'
import Markdown from './Markdown'

const Caption = () => {
	const { caption, byline } = useDataContext()
	return caption || byline ? (
		<figcaption
			className={classNames('Caption')}
		>
			<div
				className={classNames('CaptionInner')}
			>
				<Markdown
					content={caption}
				/>
				<div
					className={classNames('CaptionByline')}
				>
					{byline}
				</div>
			</div>
		</figcaption>
	) : null
}

export default Caption
