// packages/svelte/src/lib/components/Collapse.svelte
<script>
	import {
		Collapsible as ArkCollapsible,
		useCollapsible as useArkCollapsible
	} from '@ark-ui/svelte/collapsible'
	import { classNames } from 'syw-common/helpers'

	const id = $props.id();
	const { open, children } = $props();
	const arkCollapsible = useArkCollapsible(() => ({ id, open }))

	const classes = $derived(
		classNames(
			'Collapse',
			open ? 'Collapse_open' : false
		)
	)
</script>

<ArkCollapsible.RootProvider
	id={id}
	class={classes}
	value={arkCollapsible}
	aria-expanded={open}
>
	<ArkCollapsible.Content
		class={classNames('CollapseInner')}
	>
		{@render children()}
	</ArkCollapsible.Content>
</ArkCollapsible.RootProvider>

// packages/react/src/components/Collapse.jsx
import { useEffect, useMemo } from 'react'
import {
	Collapsible as ArkCollapsible,
	useCollapsible as useArkCollapsible
} from '@ark-ui/react/collapsible'
import { classNames } from 'syw-common/helpers'

const Collapse = ({
	open = false,
	children
}) => {
	const arkCollapsible = useArkCollapsible()

	const className = useMemo(() =>
		classNames(
			'Collapse',
			open ? 'Collapse_open' : false,
		)
	, [open])

	useEffect(() => {
		arkCollapsible.setOpen(open)
	}, [open])

	return (
		<ArkCollapsible.RootProvider
			value={arkCollapsible}
			aria-expanded={open}
			className={className}
		>
			<ArkCollapsible.Content
				className={classNames('CollapseInner')}
			>
				{children}
			</ArkCollapsible.Content>
		</ArkCollapsible.RootProvider>
	)
}

export default Collapse
