// packages/svelte/src/lib/components/Cutline.svelte
<script>
	import { classNames } from 'syw-common/helpers'
	import ProvenanceToggle from './ProvenanceToggle.svelte'
	import ExplainerToggle from './ExplainerToggle.svelte'
</script>

<div
	class={classNames('Cutline')}
>
	<div
		class={classNames('CutlineToggles')}
	>
		<ProvenanceToggle />
		<ExplainerToggle />
	</div>
</div>

// packages/react/src/components/Cutline.tsx
import { classNames } from 'syw-common/helpers'
import ProvenanceToggle from './ProvenanceToggle'

const Cutline = () => {
	return (
		<div
			className={classNames('Cutline')}
		>
			<div
				className={classNames('CutlineToggles')}
			>
				<ProvenanceToggle />
			</div>
		</div>
	)
}

export default Cutline
