// packages/svelte/src/lib/components/Image.svelte
<script>
	import { getContext } from 'svelte'
	import { classNames } from 'syw-common/helpers'
	import { handleA11yClick } from 'syw-common/helpers'

	const { src, alt } = getContext('dataStoreContext')
	const {
		hoverImage, unhoverImage, isProvenanceOpen, openProvenance, closeProvenance
	} = getContext('uiStoreContext')

	const handleClick = (event) => {
		if($isProvenanceOpen) {
			closeProvenance(event)
		} else {
			openProvenance(event)
		}
	}

	const handleMouseEnter = (event) => {
		hoverImage(event)
	}

	const handleMouseLeave = (event) => {
		unhoverImage(event)
	}

	const handleKeyDown = event => {
		if($isProvenanceOpen) {
			handleA11yClick(event, closeProvenance)
		} else {
			handleA11yClick(event, openProvenance)
		}
	}

</script>

<div
	class={classNames('Image')}
	role="button"
	tabindex="0"
	onclick={handleClick}
	onmouseenter={handleMouseEnter}
	onmouseleave={handleMouseLeave}
	onkeydown={handleKeyDown}
>
	<img
		src={$src}
		alt={$alt}
		class={classNames('ImageImg')}
	/>
</div>

// packages/react/src/components/Image.jsx
import { useCallback } from 'react'
import { classNames, handleA11yClick } from 'syw-common/helpers'
import { useDataContext } from '$src/context/data'
import { useUiContext } from '$src/context/ui'

const Image = () => {
	const {
		src,
		alt,
	} = useDataContext()
	const {
		hoverImage,
		unhoverImage,
		openProvenance,
		closeProvenance,
		isProvenanceOpen,
	} = useUiContext()

	const onClick = useCallback(event =>
		isProvenanceOpen
			? closeProvenance(event)
			: openProvenance(event)
	, [openProvenance, closeProvenance, isProvenanceOpen])

	const onKeyDown = useCallback(event =>
		handleA11yClick(
			event,
			isProvenanceOpen
				? closeProvenance
				: openProvenance
		)
	, [openProvenance, closeProvenance, isProvenanceOpen])

	const onMouseEnter = useCallback(event =>
		hoverImage(event)
	, [hoverImage])
	
	const onMouseLeave = useCallback(event =>
		unhoverImage(event)
	, [unhoverImage])


	return (
		<div
			className={classNames('Image')}
			onClick={onClick}
			onKeyDown={onKeyDown}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			tabIndex={0}
		>
			<img
				src={src}
				alt={alt}
				className={classNames('ImageImg')}
			/>
		</div>
	)
}

export default Image
