// packages/svelte/src/lib/components/ManifestTableRow.svelte
<script>
	import { getContext } from 'svelte';
	import { classNames } from 'syw-common/helpers'
	import { getDateString } from 'syw-common/helpers/i18n'
    import Map from './Map.svelte'
	import Actions from './Actions.svelte'

	const { locale, getText } = getContext('i18nStoreContext');

	const {
		type,
		value,
	} = $props()

	const formattedValue = $derived(() => {
		switch(type) {
			case 'producer':
				return value?.map(v => v.name).join(', ')
			case 'timestamp':
				return getDateString($locale, value)
			default:
				return value
		}
	})

</script>

<li
	class={classNames('ManifestTableRow')}
>
	<div
		class={classNames('ManifestTableRowLabel')}
	>
		{type ? getText($locale, type) : ''}
	</div>
	<div
		class={classNames('ManifestTableRowValue')}
	>
		{#if type === 'location'}
			<Map
				location={value}
			/>
		{:else if type === 'actions'}
			<Actions
				actions={value}
			/>
		{:else if type === 'generator'}
			<div>
				{formattedValue()}
				<div
					class={classNames('ManifestTableRowValueSub')}
				>
					{getText($locale, 'actions', 'count')?.replace('{count}', value?.length)}
				</div>
			</div>
		{:else}
			{formattedValue()}
		{/if}
	</div>
</li>

// packages/react/src/components/ManifestTableRow.jsx
import { useMemo } from 'react'
import { classNames } from 'syw-common/helpers'
import { getDateString } from 'syw-common/helpers/i18n'
import { useI18nContext } from '$src/context/i18n'
import Map from './Map'

function ManifestTableRow({ type, value, manifest }) {
	const { locale, getText } = useI18nContext()

	const formattedValue = useMemo(() => {
		switch(type) {
			case 'producer':
				return value?.map(v => v.name).join(', ')
			case 'timestamp':
				return getDateString(locale, value?.value)
			default:
				return value?.value || value
		}
	}, [type, value]);

	return (
		<li
			className={classNames('ManifestTableRow')}
		>
			<div
				className={classNames('ManifestTableRowLabel')}
			>
				{getText(type)}
			</div>
			<div
				className={classNames('ManifestTableRowValue')}
			>
				{type === 'location' ?
					<Map
						location={value}
					/>
				: type === 'generator' ?
					<div>
						{formattedValue}
						<div
							className={classNames('ManifestTableRowValueSub')}
						>
							{getText('actions', 'count')?.replace('{count}', value?.length)}
						</div>
					</div>
				: formattedValue}
			</div>
		</li>
	)
}

export default ManifestTableRow
