// packages/svelte/src/lib/components/ManifestContentTabsToggle.svelte
<script lang="ts">
	import { Tabs } from '@ark-ui/svelte/tabs'
	import { classNames, getAvailableTabs } from 'syw-common/helpers'
	import type { ManifestContentTabsToggleProps } from 'syw-common/types/components'
	import { getI18nContext } from '$lib/store/i18n.js'

	const {
		keys = [],
		manifest,
		class: className
	}: ManifestContentTabsToggleProps & { class?: string | null } = $props()

	const { locale, getText } = getI18nContext()

	const availableTabs = $derived(() =>
		getAvailableTabs(keys, manifest)
	)

</script>

<div
	class={classNames(
		'ManifestContentTabsToggle',
		className
	)}
>
	<Tabs.List
		class={classNames('ManifestContentTabsToggleList')}
	>
		{#each keys as key}
			<Tabs.Trigger
				value={key}
				disabled={!availableTabs().includes(key)}
				class={classNames('ManifestContentTabsToggleTrigger')}
			>
				{getText($locale, "tab", key)}
			</Tabs.Trigger>
		{/each}
		<Tabs.Indicator
			class={classNames('ManifestContentTabsToggleListIndicator')}
		/>
	</Tabs.List>
</div>

// packages/react/src/components/ManifestContentTabsToggle.tsx
import { useMemo } from 'react'
import { Tabs } from '@ark-ui/react/tabs'
import { classNames, getAvailableTabs } from 'syw-common/helpers'
import type { ManifestContentTabsToggleProps } from 'syw-common/types/components'
import { useI18nContext } from '$src/context'

function ManifestContentTabsToggle({
	manifest,
	keys,
	className
}: ManifestContentTabsToggleProps) {
	const { getText } = useI18nContext()

	const availableTabs = useMemo(() =>
		getAvailableTabs(keys, manifest)
	, [keys, manifest])

	return (
		<div
			className={classNames(
				'ManifestContentTabsToggle',
				className
			)}
		>
			<Tabs.List
				className={classNames('ManifestContentTabsToggleList')}
			>
				{keys?.map((key) => (
					<Tabs.Trigger
						key={key}
						value={key}
						disabled={!availableTabs?.includes(key)}
						className={classNames('ManifestContentTabsToggleTrigger')}
					>
						{getText("tab", key)}
					</Tabs.Trigger>
				))}
				<Tabs.Indicator
					className={classNames('ManifestContentTabsToggleListIndicator')}
				/>
			</Tabs.List>
		</div>
	)
}

export default ManifestContentTabsToggle
