// packages/svelte/src/lib/components/ProvenanceModal.svelte
<script>
	import { getContext } from 'svelte'
	// import styles from 'syw-common/css/ProvenanceModal.module.css'
	import Modal from './Modal.svelte'
	import Provenance from './Provenance.svelte'
	import Explainer from './Explainer.svelte'
	import ExplainerToggle from './ExplainerToggle.svelte'
	
	const {
		isExplainerOpen,
		isProvenanceOpen,
		openProvenance,
		closeProvenance,
		closeExplainer
	} = getContext('uiStoreContext')

	const handleOpenChange = (newOpen, event) => {
		const originalEvent = event
		if(newOpen) {
			openProvenance(originalEvent)
		} else {
			closeProvenance(originalEvent)
			closeExplainer(originalEvent)
		}
	}

</script>

<Modal
	open={$isProvenanceOpen}
	title="Image Origin"
	description="Explore the provenance of this image"
	onOpenChange={handleOpenChange}
	className='ProvenanceModal'
>
	<div
		class='ProvenanceModalExplainer'
	>
		{#if $isExplainerOpen}
			<ExplainerToggle />
		{/if}
		<Explainer />
	</div>
	<Provenance />
</Modal>

// packages/react/src/components/ProvenanceModal.jsx
import styles from 'syw-common/css/ProvenanceModal.module.css'
import { useUiContext } from '$src/context'
import Modal from './Modal'
import Provenance from './Provenance'
import Explainer from './Explainer'
import ExplainerToggle from './ExplainerToggle'

const ProvenanceModal = () => {
	const {
		isOpenExplainer,
		isOpenProvenance,
		openProvenance,
		closeProvenance,
		closeExplainer
	} = useUiContext()

	const handleOpenChange = (newOpen, event) => {
		const originalEvent = event
		if(newOpen) {
			openProvenance(originalEvent)
		} else {
			closeProvenance(originalEvent)
			closeExplainer(originalEvent)
		}
	}

	return (
		<Modal
			open={isOpenProvenance}
			title="Image Origin"
			description="Explore the provenance of this image"
			onOpenChange={handleOpenChange}
			className={styles.ProvenanceModal}
		>
			<div
				className={styles.ProvenanceModalExplainer}
			>
				{!isOpenExplainer ? <ExplainerToggle /> : null}
				<Explainer />
			</div>
			<Provenance />
		</Modal>
	)
}

export default ProvenanceModal
