// packages/svelte/src/lib/components/ProvenanceToggle.svelte
<script>
	import { getContext } from 'svelte';
	import { classNames } from 'syw-common/helpers'

	const { locale, getText } = getContext('i18nStoreContext');
	const { isProvenanceOpen, openProvenance, closeProvenance } = getContext('uiStoreContext');

	const handleClick = (event) => {
		if($isProvenanceOpen) {
			closeProvenance(event)
		} else {
			openProvenance(event)
		}
	}

</script>

<button
	aria-pressed={true}
	class={classNames('ProvenanceToggle')}
	onclick={handleClick}
>
	{$isProvenanceOpen ? getText($locale, 'toggle', 'provenance') : getText($locale, 'toggle', 'provenance')}
</button>

// packages/react/src/components/ProvenanceToggle.jsx
import { classNames } from 'syw-common/helpers'
import { useUiContext, useI18nContext } from '$src/context'

const ProvenanceToggle = () => {
	const {
		isProvenanceOpen,
		openProvenance,
		closeProvenance
	} = useUiContext()
	const { getText } = useI18nContext()

	const onClick = event => isProvenanceOpen
		? closeProvenance(event)
		: openProvenance(event)

	return (
		<button
			aria-pressed={isProvenanceOpen}
			className={classNames('ProvenanceToggle')}
			onClick={onClick}
		>
			{isProvenanceOpen ? getText('provenance', 'toggle') : getText('provenance', 'toggle')}
		</button>
	)
}

export default ProvenanceToggle
