// packages/svelte/src/lib/components/StatusBadge.svelte
<script lang="ts">
	import { classNames } from 'syw-common/helpers'
	import type { StatusBadgeProps } from 'syw-common/types/components'
	import { getI18nContext } from '$lib/store/i18n.js'
    import Badge from './Badge.svelte';

	const { locale, getText } = getI18nContext();

	const { value }: StatusBadgeProps = $props()
	const label = $derived(getText($locale, "status", value))
</script>

<Badge
	status={value}
	className={classNames("StatusBadge")}
>
	{label}
</Badge>

// packages/react/src/components/StatusBadge.tsx
import { classNames } from 'syw-common/helpers'
import type { StatusBadgeProps } from 'syw-common/types/components'
import { useI18nContext } from '$src/context/i18n'
import Badge from './Badge'

const StatusBadge = ({
	value
}: StatusBadgeProps) => {
	const { getText } = useI18nContext()
	const label = getText("status", value)
	return (
		<Badge
			status={value}
			className={classNames("StatusBadge")}
		>
			{label}
		</Badge>
	)
}

export default StatusBadge
