// packages/svelte/src/lib/components/StatusBadge.svelte
<script>
	import { classNames } from 'syw-common/helpers'
	import { getI18nContext } from '$lib/store/i18n.js'
    import Badge from './Badge.svelte';

	const { locale, getText } = getI18nContext();

	const { value } = $props()
	const label = $derived(() => getText($locale, "status", value))
	const definition = $derived(() => getText($locale, "status", value, "definition"))
</script>

<Badge
	type="status"
	value={value}
	icon={value}
	tooltip={definition()}
	className={classNames("StatusBadge")}
>
	{label()}
</Badge>

// packages/react/src/components/StatusBadge.jsx
import { classNames } from 'syw-common/helpers'
import { useI18nContext } from '$src/context/i18n'
import Badge from './Badge'

const StatusBadge = ({
	value
}) => {
	const { getText } = useI18nContext()
	const label = getText("status", value)
	const definition = getText("status", value, "definition")
	return (
		<Badge
			type="status"
			icon={value}
			value={value}
			tooltip={definition}
			className={classNames("StatusBadge")}
		>
			{label}
		</Badge>
	)
}

export default StatusBadge
