// packages/svelte/src/lib/components/ToggleProvenance.svelte
<script>
	import styles from '$common/css/ToggleProvenance.module.scss'
	import { locale, getText } from '$lib/store/i18n.js'
	import { isShowProvenance, toggleProvenance } from '$lib/store/ui.js'

	const handleClick = () => {
		toggleProvenance()
	}

</script>

<button
	aria-pressed={true}
	class={styles.ToggleProvenance}
	on:click={handleClick}
>
	{$isShowProvenance ? getText($locale, 'toggle', 'provenance') : getText($locale, 'toggle', 'provenance')}
</button>

// packages/react/src/components/ToggleProvenance.jsx
import React from 'react'

import styles from '$common/css/ToggleProvenance.module.scss'
import { useUiContext, useI18nContext } from '$src/context'

const ToggleProvenance = () => {
	const {
		isShowProvenance,
		toggleProvenance,
	} = useUiContext()
	const { locale, getText } = useI18nContext()

	const onClick = toggleProvenance

	return (
		<button
			aria-pressed={isShowProvenance}
			className={styles.ToggleProvenance}
			onClick={onClick}
		>
			{isShowProvenance ? getText('toggle', 'provenance') : getText('toggle', 'provenance')}
		</button>
	)
}

export default ToggleProvenance
