// packages/svelte/src/lib/components/ToggleExplainer.svelte
<script>
	import { getContext } from 'svelte';
	import styles from 'syw-common/css/ToggleExplainer.module.scss'

	const { locale, getText } = getContext('i18nStoreContext');
	const { isExplainerOpen, openExplainer, closeExplainer } = getContext('uiStoreContext');

	const handleClick = (event) => {
		if($isExplainerOpen) {
			closeExplainer(event)
		} else {
			openExplainer(event)
		}
	}
</script>

<button
	aria-pressed={$isExplainerOpen}
	class={styles.ToggleExplainer}
	on:click={handleClick}
>
	{getText($locale, 'toggle', 'explain')}
</button>

// packages/react/src/components/ToggleExplainer.jsx
import styles from 'syw-common/css/ToggleExplainer.module.scss'
import { useUiContext, useI18nContext } from '$src/context'

const ToggleExplainer = () => {
	const {
		isOpenExplainer,
		openExplainer,
		closeExplainer,
	} = useUiContext()
	const { getText } = useI18nContext()

	const onClick = event => isOpenExplainer
		? closeExplainer(event)
		: openExplainer(event)

	return (
		<button
			className={styles.ToggleExplainer}
			aria-pressed={isOpenExplainer}
			onClick={onClick}
		>
			{getText('toggle', 'explain')}
		</button>
	)
}

export default ToggleExplainer
