// packages/svelte/src/lib/components/Tooltip.svelte
<script lang="ts">
	import type { ComponentProps, Snippet } from 'svelte'
	import { Portal as ArkPortal } from '@ark-ui/svelte/portal'
	import { Tooltip as ArkTooltip } from '@ark-ui/svelte/tooltip'
	import { classNames } from 'syw-common/helpers'

	export interface TooltipProps {
		content?: string
		disabled?: boolean
		ContentProps?: ComponentProps<typeof ArkTooltip.Content>
		className?: string
		children?: Snippet
	}

	const {
		content,
		disabled,
		ContentProps = {},
		className,
		children
	}: TooltipProps = $props()

</script>

{#if disabled || content === undefined}
	{@render children?.()}
{:else}
	<ArkTooltip.Root
		openDelay={0}
		lazyMount={true}
		unmountOnExit={true}
	>
		<ArkTooltip.Trigger
			class={classNames(
				'TooltipTrigger',
				className,
			)}
		>
			{@render children?.()}
		</ArkTooltip.Trigger>
		<ArkPortal>
			<ArkTooltip.Positioner
				class={classNames('TooltipPositioner')}
			>
				<ArkTooltip.Content
					{...ContentProps}
					class={classNames(
						'TooltipContent',
						ContentProps?.className,
					)}
				>
					<ArkTooltip.Arrow
						class={classNames('TooltipArrow')}
					>
						<ArkTooltip.ArrowTip
							class={classNames('TooltipArrowTip')}
						/>
					</ArkTooltip.Arrow>
					{content}
				</ArkTooltip.Content>
			</ArkTooltip.Positioner>
		</ArkPortal>
	</ArkTooltip.Root>
{/if}

// packages/react/src/components/Tooltip.tsx
import { Tooltip as ArkTooltip } from '@ark-ui/react/tooltip'
import { Portal as ArkPortal } from '@ark-ui/react/portal'
import type { ComponentProps, ReactNode } from 'react'
import { classNames } from 'syw-common/helpers'

export interface TooltipProps {
	content?: ReactNode
	disabled?: boolean
	ContentProps?: ComponentProps<typeof ArkTooltip.Content>
	children: ReactNode
	className?: string
}

const Tooltip = ({
	content,
	disabled,
	ContentProps = {},
	children,
	className
}: TooltipProps) => {
	if (disabled || content === undefined) return children;
	return (
		<ArkTooltip.Root
			openDelay={0}
			lazyMount={true}
			unmountOnExit={true}
		>
			<ArkTooltip.Trigger
				className={classNames(
					'TooltipTrigger',
					className,
				)}
			>
				{children}
			</ArkTooltip.Trigger>
			<ArkPortal>
				<ArkTooltip.Positioner
					className={classNames('TooltipPositioner')}
				>
					<ArkTooltip.Content
						{...ContentProps}
						className={classNames(
							'TooltipContent',
							ContentProps?.className,
						)}
					>
						<ArkTooltip.Arrow
							className={classNames('TooltipArrow')}
						>
							<ArkTooltip.ArrowTip
								className={classNames('TooltipArrowTip')}
							/>
						</ArkTooltip.Arrow>
						{content}
					</ArkTooltip.Content>
				</ArkTooltip.Positioner>
			</ArkPortal>
		</ArkTooltip.Root>
	)
}

export default Tooltip
