// packages/svelte/src/lib/components/Tooltip.svelte
<script>
	import { Portal as ArkPortal } from '@ark-ui/svelte/portal'
	import { Tooltip as ArkTooltip } from '@ark-ui/svelte/tooltip'
	import { classNames } from 'syw-common/helpers'

	const {
		content,
		ContentProps = {},
		className,
		children
	} = $props()

</script>

<ArkTooltip.Root
	openDelay={0}
	lazyMount={true}
	unmountOnExit={false}
	disabled={content === undefined}
>
	<ArkTooltip.Trigger
		class={classNames(
			'TooltipTrigger',
			className,
		)}
	>
		{@render children?.()}
	</ArkTooltip.Trigger>
	<ArkPortal>
		<ArkTooltip.Positioner>
			<ArkTooltip.Content
				{...ContentProps}
				class={classNames(
					'TooltipContent',
					ContentProps?.className,
				)}
			>
				<ArkTooltip.Arrow
					class={classNames('TooltipArrow')}
				>
					<ArkTooltip.ArrowTip
						class={classNames('TooltipArrowTip')}
					/>
				</ArkTooltip.Arrow>
				{content}
			</ArkTooltip.Content>
		</ArkTooltip.Positioner>
	</ArkPortal>
</ArkTooltip.Root>

// packages/react/src/components/Tooltip.jsx
import { Tooltip as ArkTooltip } from '@ark-ui/react/tooltip'
import { Portal as ArkPortal } from '@ark-ui/react/portal'
import { classNames } from 'syw-common/helpers'

const Tooltip = ({
	content,
	disabled,
	ContentProps = {},
	children,
	className
}) => {
	if (disabled || content === undefined) return children;
	return (
		<ArkTooltip.Root
			openDelay={0}
			lazyMount={true}
			unmountOnExit={true}
		>
			<ArkTooltip.Trigger
				className={classNames(
					'TooltipTrigger',
					className,
				)}
			>
				{children}
			</ArkTooltip.Trigger>
			<ArkPortal>
				<ArkTooltip.Positioner
					className={classNames('TooltipPositioner')}
				>
					<ArkTooltip.Content
						{...ContentProps}
						className={classNames(
							'TooltipContent',
							ContentProps?.className,
						)}
					>
						<ArkTooltip.Arrow
							className={classNames('TooltipArrow')}
						>
							<ArkTooltip.ArrowTip
								className={classNames('TooltipArrowTip')}
							/>
						</ArkTooltip.Arrow>
						{content}
					</ArkTooltip.Content>
				</ArkTooltip.Positioner>
			</ArkPortal>
		</ArkTooltip.Root>
	)
}

export default Tooltip
