// packages/svelte/src/lib/components/TypeBadge.svelte
<script lang="ts">
	import { classNames } from 'syw-common/helpers'
	import type { TypeBadgeProps } from 'syw-common/types/components'
	import { getI18nContext } from '$lib/store/i18n.js'
    import Badge from './Badge.svelte';

	const { locale, getText } = getI18nContext();

	const { value, status }: TypeBadgeProps = $props()

	const label = $derived(getText($locale, "type", value?.key ?? ''))
</script>

<Badge
	type={value}
	status={status}
	className={classNames(
		"TypeBadge",
		status ? `Badge_status_${status}` : null
	)}
>
	{label}
</Badge>

// packages/react/src/components/TypeBadge.tsx
import { classNames } from 'syw-common/helpers'
import type { TypeBadgeProps } from 'syw-common/types/components'
import { useI18nContext } from '$src/context/i18n'
import Badge from './Badge'

const TypeBadge = ({
	value,
	status
}: TypeBadgeProps) => {
	const { getText } = useI18nContext()
	const label = getText("type", value?.key ?? '')
	return (
		<Badge
			type={value}
			status={status}
			className={classNames(
				"TypeBadge",
				status ? `Badge_status_${status}` : null
			)}
		>
			{label}
		</Badge>
	)
}

export default TypeBadge
