// packages/svelte/src/lib/components/Video.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { classNames } from 'syw-common/helpers'
	import { getDataContext } from '$lib/store/data.js'

	let mounted = $state(false);
	const { src, alt } = getDataContext()

	onMount(async () => {
		await import('@videojs/html/video/player');
		await import('@videojs/html/video/skin');
		await import('@videojs/html/video/skin.css');
		mounted = true;
	});

</script>

<div
	class={classNames('Video')}
>
	{#if mounted}
		<video-player>
			<video-skin
				class={classNames('VideoSkin')}
			>
				<!-- svelte-ignore a11y_media_has_caption -->
				<video
					src={$src}
					aria-label={$alt}
					slot="media"
					class={classNames('Video')}
				>
					<!-- <track kind="captions"> -->
				</video>
			</video-skin>
		</video-player>
	{/if}
</div>

// packages/react/src/components/Video.tsx
import '@videojs/react/video/skin.css'
import { createPlayer, videoFeatures } from '@videojs/react'
import { VideoSkin, Video as VideoJs } from '@videojs/react/video'
import { classNames } from 'syw-common/helpers'
import { useDataContext } from '$src/context/data'

const Player = createPlayer({
	features: videoFeatures
})

const Video = () => {
	const {
		src,
		alt,
	} = useDataContext()
	return (
		<div
			className={classNames('Video')}
		>
			<Player.Provider>
				<VideoSkin
					className={classNames('VideoSkin')}
				>
					<VideoJs
						src={src ?? undefined}
						aria-label={alt ?? undefined}
						playsInline
						className={classNames('Video')}
					/>
				</VideoSkin>
			</Player.Provider>
		</div>
	)
}

export default Video
